const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const envPath = path.join(projectRoot, '.env.local');
const outDir = path.join(projectRoot, 'assets');
const outFile = path.join(outDir, 'env.js');

function parseEnv(content) {
  const lines = content.split(/\r?\n/);
  const result = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.substring(0, idx).trim();
    let val = trimmed.substring(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.substring(1, val.length - 1);
    }
    result[key] = val;
  }
  return result;
}

if (!fs.existsSync(envPath)) {
  console.warn('.env.local not found — skipping env injection. Create .env.local with GEMINI_API_KEY or UNSPLASH_ACCESS_KEY to enable.');
  process.exit(0);
}

const content = fs.readFileSync(envPath, 'utf8');
const env = parseEnv(content);
const geminiKey = env.GEMINI_API_KEY || env.API_KEY || '';
const unsplashKey = env.UNSPLASH_ACCESS_KEY || env.UNSPLASH_KEY || '';

if (!geminiKey && !unsplashKey) {
  console.warn('No GEMINI_API_KEY or UNSPLASH_ACCESS_KEY found in .env.local — skipping env injection.');
  process.exit(0);
}

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

let fileContent = `// Auto-generated by scripts/inject-env.cjs — do not commit\ntry {\n`;
if (geminiKey) {
  fileContent += `  window.GEMINI_API_KEY = ${JSON.stringify(geminiKey)};\n  console.log('[inject-env] GEMINI_API_KEY injected');\n`;
}
if (unsplashKey) {
  fileContent += `  window.UNSPLASH_ACCESS_KEY = ${JSON.stringify(unsplashKey)};\n  console.log('[inject-env] UNSPLASH_ACCESS_KEY injected');\n`;
}
fileContent += `} catch (e) {\n  // ignore when not running in browser context\n}\n`;
fs.writeFileSync(outFile, fileContent, 'utf8');
console.log('Wrote', outFile);
